UPDATE RELATIONSHIP
SET ActorId = 'AC102'
WHERE RelationId = 'R101';

UPDATE RELATIONSHIP
SET ActorId = 'AC104'
WHERE RelationId = 'R102';

UPDATE RELATIONSHIP
SET ActorId = 'AC105'
WHERE RelationId = 'R103';

UPDATE RELATIONSHIP
SET ActorId = 'AC102'
WHERE RelationId = 'R104';